# Generated by Django 4.2.20 on 2025-04-22 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models.project


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.project.project_thumbnail_upload_to),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', projects.models.project.ULIDField(default=projects.models.project.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
