# Generated by Django 4.2.20 on 2025-04-22 15:09

from django.db import migrations, models
import projects.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_role_projectmemberrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=projects.models.project.ULIDField(default=projects.models.project.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True),
        ),
    ]
