# Generated by Django 4.2.20 on 2025-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_role_display_name_alter_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
