# Generated by Django 4.2.20 on 2025-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_joined_at_projectmember_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
