# Generated by Django 4.2.20 on 2025-04-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_sub_domain'),
        ('projects', '0007_rename_assigned_at_projectmemberrole_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(default='01JSS0RP8PS1SAB3X76DEE96MB', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
