# Generated by Django 4.2.20 on 2025-04-26 07:49

from django.db import migrations, models
import django.db.models.deletion
import shared.models.ulid_field


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', shared.models.ulid_field.ULIDField(default=shared.models.ulid_field.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationUserRole',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', shared.models.ulid_field.ULIDField(default=shared.models.ulid_field.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('organization_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_roles', to='organizations.organizationuser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationrole')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
