# Generated by Django 4.2.20 on 2025-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationrole_organizationuserrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sub_domain',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
