# Generated by Django 4.2.20 on 2025-04-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_sub_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='sub_domain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
